version: '3'

networks:
  inception:
    driver: bridge  

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ml/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ml/data/mariadb'
  website:
    name: website
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ml/data/website'
  portainer:  # Définition du volume pour Portainer
    name: portainer
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ml/data/portainer'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    expose:
      - "3306"
    env_file: 
      - .env
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks: 
      - inception
    env_file: 
      - .env
    restart: always

  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks: 
      - inception
    env_file: 
      - .env
    restart: always

  ftp:
    container_name: ftp
    build:
      context: requirements/bonus/ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"  # Ajout de la plage de ports pour le mode passif
    volumes:
      - wordpress:/var/www/html
    networks: 
      - inception
    env_file: 
      - .env
    restart: always

  website:
    container_name: website
    build:
      context: requirements/bonus/website
    ports:
      - "1111:1111"
    volumes:
      - website:/var/www/html
    networks: 
      - inception
    env_file: 
      - .env
    restart: always

  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
    expose:
      - "9000"
    depends_on:
      - mariadb
      - wordpress
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file: 
      - .env
    restart: always

  portainer:
    container_name: portainer
    build:
      context: requirements/bonus/portainer
    networks:
      - inception
    ports:
      - "9443:9443"
    networks: 
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always