#base image 

FROM debian:bullseye

RUN apt update && apt upgrade -y && apt install -y nginx

#execute cmd in container
#RUN

#copy or download files in image
#ADD

#modify current repository (=cd)
#WORKDIR


#Indicate the port who is the application listenning
#EXPOSE

#Indicate what repository to share with the host
#VOLUME

#Les instructions EXPOSE et VOLUME ne sont pas 
#nécessaires au bon fonctionnement de notre image
# Docker. Cependant, les ajouter permet une meilleure 
#compréhension pour l’utilisateur des ports d'écoute attendus, 
#ainsi que des volumes partageables.

#This ligne permite to our container to know the commande he needs to exectue when is started
#CMD || ENTRYPOINT

